Repository ChanunyaO/KU-Lend, pull requests merged in 2021-11, with the labels that each got.

#30 save borrower's name and email
  ku_lend/migrations/0001_initial.py
  ku_lend/migrations/0002_alter_item_amount_items.py
  ku_lend/migrations/0002_remove_history_borrower_note.py
  ku_lend/migrations/0003_alter_history_borrower_fee.py
  ku_lend/models.py
  ku_lend/views.py
Labels: Improvement

#31 Send reminder function
  Screen_Shot_2564-11-06_at_11.25.29.png
  ku_lend/function/reminder.py
  ku_lend/views.py
  mysite/settings.py
  requirements.txt
Labels: enhancement

#34 Bill
  .gitignore
  ku_lend/function/bill.py
  ku_lend/migrations/0003_history_late_day.py
  ku_lend/models.py
  ku_lend/views.py
Labels: enhancement

#32 Index page
  Tablet.jpg
  Tablet_bar4VUo.jpg
  ku_lend/templates/ku_lend/borrow_form.html
  ku_lend/templates/ku_lend/index.html
  ku_lend/templates/ku_lend/layout.html
  ku_lend/templates/ku_lend/profile.html
  ku_lend/views.py
  mysite/asgi.py
  mysite/settings.py
  mysite/wsgi.py
Labels: Improvement

#39 add more to models
  ku_lend/migrations/0001_initial.py
  ku_lend/models.py
Labels: Improvement

#41 add borrow amount to History model
  ku_lend/migrations/0001_initial.py
  ku_lend/models.py
Labels: Improvement

#42 save more borrowing detail and send confirm mail
  ku_lend/function/confirm_mail.py
  ku_lend/views.py
Labels: Improvement

#43 Form page
  ku_lend/templates/ku_lend/borrow_form.html
  ku_lend/templates/ku_lend/index.html
  ku_lend/templates/ku_lend/profile.html
  ku_lend/views.py
Labels: Improvement

#45 Add auto send-mail
  Procfile
  clock.py
  ku_lend/function/reminder.py
  requirements.txt
Labels: enhancement, Improvement

#49 Email testing
  ku_lend/function/avaliable.py
  ku_lend/function/bill.py
  ku_lend/function/confirm_mail.py
  ku_lend/function/fee.py
  ku_lend/function/reminder.py
  ku_lend/tests.py
  ku_lend/tests/__init__.py
  ku_lend/tests/test_emails.py
  ku_lend/urls.py
  ku_lend/views.py
  mysite/settings.py
Labels: Test

#56 Fix logout
  .env.template
  README.md
  ku_lend/fixtures/item.json
  ku_lend/fixtures/site.json
  ku_lend/fixtures/users.json
  mysite/settings.py
Labels: Improvement

#57 add condition
  ku_lend/function/reminder.py
Labels: Improvement

#58 Test email
  ku_lend/tests/test_emails.py
Labels: Improvement, Test

#60 Form page improvement
  ku_lend/templates/ku_lend/borrow_form.html
  ku_lend/templates/ku_lend/index.html
Labels: Improvement

#61 improve index page
  ku_lend/templates/ku_lend/index.html
Labels: Improvement

#70 add return condition
  ku_lend/function/bill.py
Labels: Improvement, Test

#59 E2E test profile
  ku_lend/templates/ku_lend/index.html
  ku_lend/tests/test_e2e_profile.py
  requirements.txt
Labels: Test

#68 E2e test form
  Unknown.jpg
  ku_lend/templates/ku_lend/borrow_form.html
  ku_lend/tests/test_e2e_form.py
Labels: Test

#69 add test_e2e
  ku_lend/tests/test_e2e_login.py
Labels: Test

#71 Deploy web from main v3
  .env.template
  README.md
  ku_lend/fixtures/item.json
  ku_lend/fixtures/site.json
  ku_lend/fixtures/users.json
  ku_lend/function/avaliable.py
  ku_lend/function/bill.py
  ku_lend/function/confirm_mail.py
  ku_lend/function/fee.py
  ku_lend/function/reminder.py
  ku_lend/migrations/0001_initial.py
  ku_lend/models.py
  ku_lend/templates/ku_lend/borrow_form.html
  ku_lend/templates/ku_lend/index.html
  ku_lend/templates/ku_lend/profile.html
  ku_lend/tests.py
  ku_lend/tests/__init__.py
  ku_lend/tests/test_e2e_form.py
  ku_lend/tests/test_e2e_login.py
  ku_lend/tests/test_e2e_profile.py
  ku_lend/tests/test_e2e_staff.py
  ku_lend/tests/test_emails.py
  ku_lend/tests/test_fee.py
  ku_lend/tests/tests_items.py
  ku_lend/urls.py
  ku_lend/views.py
  mysite/settings.py
  requirements.txt
Labels: Improvement

#82 fix bug
  ku_lend/templates/ku_lend/borrow_form.html
  mysite/settings.py
Labels: bug

#84 disable typing date input
  ku_lend/templates/ku_lend/borrow_form.html
Labels: bug

#86 Add Cancel Button
  ku_lend/function/bill.py
  ku_lend/templates/ku_lend/profile.html
  ku_lend/urls.py
  ku_lend/views.py
Labels: Improvement

#87 Main for deploy v5
  README.md
  ku_lend/function/bill.py
  ku_lend/templates/ku_lend/borrow_form.html
  ku_lend/templates/ku_lend/profile.html
  ku_lend/urls.py
  ku_lend/views.py
  mysite/settings.py
Labels: Improvement

#89 wording improvement
  ku_lend/templates/ku_lend/borrow_form.html
Labels: Improvement
